import React from 'react';
import Header from './components/Header';

function Agb() {
  return (<div className='info'>
    <br /><br />
    <h3><strong>Allgemeine Geschäftsbedingungen</strong></h3>  <br />
    Veröffentlicht am 20. Mai 2022<br /><br />
    Datum des Inkrafttretens: 20. Mai 2022<br />
    <br />
    Kontakt<br />
    Telefon: +49 1577 9683734<br />
    E-Mail: info@lokalpetition.de<br />
    <br /><br />
    1. Wesen des Angebotes<br /><br />
    Vielen Dank für dein Interesse an Lokalpetition! Unter der Domain lokalpetition.de bietet die LocalPetition UG (haftungneschränkt), vertreten durch Felix Scherf (im Folgenden: „Lokalpetition“, oder „wir“) eine auf Bürgerbeteiligung ausgerichtete Website mit vorwiegend nutzergenerierten Inhalten.  Lokalpetition stellt hierzu die technische Plattform. Eigene Inhalte bietet Lokalpetition auf Lokalpetition.de in der Regel nicht an.  Lokalpetition wird hinsichtlich der Inhalte stets nur als Vermittler tätig.  Für fremde Inhalte übernimmt Lokalpetition keine Haftung.  Lokalpetition kann nicht für eine gegebenenfalls angegebene Identität eines Nutzers einstehen.  Lokalpetition behält sich vor, die angebotenen Dienste zu ändern, einzustellen oder neue Dienste anzubieten. <br />
    Die vorliegenden Allgemeinen Geschäftsbedingungen („AGB“) regeln deinen Zugriff auf Lokalpetition.de.  In unserer Datenschutzrichtlinie wird erläutert, wie wir deine Daten erheben und verwenden, während hier deine Pflichten hinsichtlich der Nutzung von Lokalpetition dargelegt werden.  Durch die Registrierung erklärst du dich mit diesen AGB und unserer Datenschutzrichtlinie einverstanden. <br />
    <br /><br />
    2. Registrierung<br /><br />
    Jeder Nutzer, der aktiv an der Kommunikation teilnehmen möchte (sich mit anderen Nutzern austauschen, Inhalte einstellen möchte, für Ideen voten möchte etc. ), muss sich hierzu bei Lokalpetition registrieren.  Durch die Registrierung entstehen dem Nutzer keine Kosten.  Die Registrierung bei Lokalpetition erfolgt unter Lokalpetition.de.  Es wird ein frei wählbarer Nutzername von dem Nutzer benötigt.  Der Nutzer wählt bei seiner Registrierung ein Passwort.  Er verpflichtet sich, dieses Passwort geheim zu halten.  Kein Nutzer darf mehr als ein Nutzerprofil registrieren. <br />
    <br />3. Verfügbarkeit und Nutzung des Angebotes<br /><br />
    Grundsätzlich steht die Nutzung jeder natürlichen und geschäftsfähigen Person, die gewillt ist sich an diese Nutzungsbedingungen zu halten und zu den Themen und Inhalten konstruktiv beizutragen, frei.der Zugang zum Angebot und dessen Nutzung, kann jedoch nicht rechtlich beansprucht werden, wir behalten uns in jedem Fall unsere Zustimmung vor. Eine uneingeschränkte Verfügbarkeit des Angebots für die Nutzer ist technisch nicht zu leisten, da unser Angebot Zugriff auf Telekommunikationsnetze und -verbindungen anderer Netzbetreiber und anderer Diensteanbieter voraussetzt, auf deren Leistungen wir keinen Einfluss haben. Soweit wir Einfluss auf Unterbrechungen, z. B.  notwendige Maßnahmen (wie Pflege- und Wartungsarbeiten an Software) haben, sind wir bemüht Unterbrechungen des Angebotes zeitlich so kurz wie möglich zu halten und diese ggf. auch anzukündigen. <br /> <br />
    4.  Nutzerpflichten und besondere Nutzungsbedingungen<br /><br />
    Grundlage der Nutzung, sind die nachfolgenden Bestimmungen, die wesentliche Vertragspflichten der Nutzer enthalten:<br /><br />
    4.1 Unzulässige Inhalte, kommerzielle Werbung, unerlaubte Nutzungsweisen, Links<br /><br />
    Wir weisen ausdrücklich darauf hin, dass folgende Nutzungshandlungen oder Inhalte nicht zulässig sind und wir bereits bei einem ersten Zuwiderhandeln neben der Entfernung des Inhalts bzw. Beitrags weitere Konsequenzen bis zu einer sofortigen Sperrung des Nutzers für alle Dienste ziehen werden:<br />
    <br /><br />
    -Alle Beiträge, Tätigkeiten und Handlungen, die gesetzeswidrige, insbesondere beleidigende, pornographische oder sonst gegen Jugendschutzbestimmungen verstoßende Handlungen darstellen oder diese verherrlichen, sowie alle Beiträge, in denen natürliche oder juristische Personen sonst in ihrer Ehre bzw.dem geschäftlichen Ansehen herabgesetzt oder ihr geschäftlicher oder sonstiger Ruf geschädigt wird. <br />
    -Das Offenlegen oder zugänglich machen von persönlichen Zugangsdaten zu Lokalpetition, seien es eigene Daten oder fremde Daten. Die Verletzung von Urheber- oder Markenrechten Dritter, insbesondere im Falle eines Verstoßes gegen die nachfolgende Ziffer 4. 2 Jede Form von Diskriminierung anderer Menschen sowie sonstige schwerwiegende Verstöße gegen die Netiquette. <br />
    -Das Setzen von Links zu anderen Seiten oder Diensten, die gesetzeswidrigen, beleidigenden oder pornografischen Inhalt oder sonst unerwünschte Inhalte aufweisen sowie jede Form von Werbung oder kommerzieller Nutzung ohne unsere ausdrückliche vorherige Zustimmung. <br />
    -Das Setzen von Links zu anderen Seiten oder Diensten, die gesetzeswidrigen, beleidigenden oder pornografischen Inhalt oder sonst unerwünschte Inhalte aufweisen sowie jede Form von Werbung oder kommerzieller Nutzung ohne unsere ausdrückliche vorherige Zustimmung. <br />
    -Das automatische Auslesen der auf unserer Seite befindlichen Daten sowie der Aufbau eigener Suchsysteme, Dienste und Verzeichnisse unter Zuhilfenahme der auf Lokalpetition.de abrufbaren Inhalte sowie das massenhafte Erstellen von inhaltsgleichen Beiträgen und/oder Antworten, auch Crosspostings, also das Posten des gleichen Beitrags in mehreren Foren. Dies gilt auch für Kurzmitteilungen. <br />
    -Ferner das Versenden von Kettenmails bzw. -briefen per Mail, jegliche Durchführung von Strukturvertrieb bzw.  -vertriebsunterstützung, auch sog. Multi-level-marketing. Das Hochladen von Software, Skripten, Dateien und sonstigen Mechanismen/Techniken, die dazu geeignet sind, Lokalpetition.de oder dessen User, deren Computer, die Server von Lokalpetition.de oder die auf den Rechnern der User oder den Servern von Lokalpetition.de verwendete Software, auszuspionieren, zu attackieren, lahm zu legen oder in sonstiger Form zu beeinträchtigen oder zu einer Beeinträchtigung Beihilfe zu leisten. <br />
    <br />Unerwünscht sind außerdem folgende Nutzungshandlungen und Inhalte:
    <br /><br />
    
    -Beiträge oder Kommunikation mit erotischem oder sexuell geprägten Inhalt. <br />
    -Beiträge mit Kritik an Produkten, Firmen, Restaurants etc. , es sei denn, der gesamte Vorgang wird sachlich vorgetragen und ist durch den jeweiligen Nutzer auch in vollem Umfang nachweisbar. <br />
    -Das Setzen von Links ist nur erlaubt, wenn diese zu gewünschten Informationen im Sinne von Lokalpetition dienen. Über die Zulässigkeit entscheiden wir im Einzelfall, sobald wir Kenntnis von einem Link erhalten. Da wir eine Haftung von unserer Seite für die von unseren Nutzern gesetzten Links nach heute geltender Rechtsprechung nicht mit völliger rechtlicher Sicherheit auch für die Zukunft ausschließen können, behalten wir uns vor, auch Links, die einmal zugelassen worden sind, zu einem späteren Zeitpunkt ohne Angabe von Gründen jederzeit von unserer Seite zu entfernen. Die Nutzer, deren Links zugelassen worden sind, verpflichten sich, die Inhalte der gelinkten Seiten regelmäßig zu prüfen und uns im Zweifel davon zu unterrichten, dass sich diese Inhalte geändert haben. Wir bitten alle Nutzer, uns auf etwaige unzulässige Beiträge, Links oder Etikett Verstöße durch die Betätigung der dafür vorgesehenen Melde-buttons oder eine Mail an info@Lokalpetition.de hinzuweisen. <br />
    <br /><br />
    4.2 Urheber- und Nutzungsrechte, gewerbliche Schutzrechte und Markenrechte, Haftung<br /><br />
    Alle Nutzer erklären sich damit einverstanden, dass Lokalpetition für die Plattform Lokalpetition.de von ihnen zur Verfügung gestellten Daten (Texte) auch nach Einstellung der Nutzung durch den Nutzer noch für die Dauer des Bestehens des gesetzlichen Urheberrechtes weiterhin von Lokalpetition selbst oder durch Lokalpetition benannte Dritte für die Zwecke des Portalbetriebes elektronisch vervielfältigt und zum Download (§ 19 UrhG) bereitgehalten werden dürfen. Darüber hinaus darf Lokalpetition die Inhalte im Rahmen seines Newsletters per Mail an andere Nutzer versenden und Dritten gestatten, per RSS-Feed auf die Inhalte zurückzugreifen und diese auf ihren Internetseiten zum download anzubieten. Die Nutzer stehen dafür ein, dass die von ihnen eingestellten bzw. zur Verfügung gestellten Daten, wie vorstehend beschrieben, genutzt und veröffentlicht werden dürfen.  Schadensersatzansprüche gegen Lokalpetition können nur geltend gemacht werden, wenn wir schuldhaft gegen unsere wesentlichen Vertragspflichten verstoßen haben. Trifft uns nur ein sehr geringes Verschulden oder sind nur unwesentliche Nebenpflichten verletzt, schließen wir jede Haftung unsererseits aus, wobei Ansprüche nach dem Produkthaftungsgesetz unberührt bleiben.der Höhe nach sind alle etwaigen Schadensersatzansprüche unserer Nutzer gegen uns beschränkt auf den vorhersehbaren Schaden. Dies gilt nicht für Ansprüche aus dem Produkthaftungsgesetz sowie bei Verletzung von Leben, Körper und Gesundheit. <br />
    <br /><br />
    4.3 Umgangston und Netiquette<br /><br />
    Wir sind berechtigt, die Entscheidung über die Eignung von Beiträgen für uns zu treffen und auch berechtigt, Beiträge ohne Angabe von Gründen zu entfernen. Alle Nutzer sind verpflichtet, sich in Umgangston und Netiquette an die Grundregeln der gegenseitigen Toleranz und des höflichen Umgangs zu halten. Als solche setzen wir voraus: Höflichkeit – mindestens ein „Hallo“, „Bitte“, „Danke“ und ein Gruß gehören zum Anstand. Keine Herabsetzungen oder Beleidigungen, im Zweifel noch einmal genau prüfen und abwägen, was man geschrieben hat. Wer an einem echten Meinungsaustausch nicht teilnehmen möchte, weil er z. B. darauf beharrt, dass seine Meinung die einzig wahre ist, sollte sich einen öffentlichen Disput ersparen. Im Zweifel richtet man sich nach den Regeln der Gemeinschaft, insbesondere, wenn man ihr angehören möchte. Alle Herabsetzungen und persönlichen Angriffe werden auf Lokalpetition.de nicht toleriert, ungeachtet dessen, ob sich solche Äußerungen direkt gegen die anderen Nutzer, gegen Dritte oder gegen andere interne oder externe beteiligte oder unbeteiligte Personengruppen richten.  Gleiches gilt für alle Beiträge, die gegen geltendes Recht verstoßen. <br />
    <br /><br />
    6.  Moderation und Rechte<br /><br />
    Wir stellen die Einhaltung der Nutzungsbedingungen sicher, wenn nötig auch durch das Sperren, oder Löschen von Beiträgen oder den Ausschluss von Mitgliedern. Diese Maßnahmen werden im Sinne der Nutzungsbedingungen und im Sinne eines guten Forenklimas durchgeführt und unterliegen keinerlei Erklärungspflicht. Wir tun dies im Interesse aller Nutzer. Es ist Lokalpetition infolge der Vielzahl von Kommunikationsvorgängen und –angeboten nicht möglich, diese vollständig zur Kenntnis zu nehmen. Wir bitten alle Nutzer, uns auf etwaige unseriöse oder ungesetzliche Verhaltensweisen durch die Betätigung der dafür vorgesehenen Meldebuttons und einer Mail an info@Lokalpetition.de hinzuweisen. <br />
    Beendigung der Nutzung<br />
    Jeder Nutzer kann die unentgeltliche Nutzungsmöglichkeit jederzeit ohne Angabe von Gründen beenden. Hierfür sollte er sich nicht mehr einloggen oder den dafür vorgesehenen Konto-löschen-Button betätigen und uns durch eine Mail an info@Lokalpetition.de darauf hinweisen.  Eingestellte Inhalte und der Benutzername bleiben nach einer Beendigung nicht mehr Bestandteil des öffentlich abrufbaren Inhaltsangebots bestehen.  <br />
    <br /><br />7.  Datenschutz, Einwilligung des Nutzers<br /><br />
    Die von den Nutzern in das Benutzerkonto eingegebenen personenbezogenen Daten, bzw. die E-Mail Adresse, der Nutzername, Alter und Geschlecht werden von Lokalpetition.de nicht an Dritte weitergegeben. Die E-Mail-Adresse kann verwendet werden, um NutzerInnen in Bezug auf ihre Aktivitäten auf Lokalpetition.de zu kontaktieren. Das Nutzerkonto und der zugehörige Benutzername selbst können nicht entfernt oder geändert werden. Die vorgenannte Einwilligung kann jederzeit durch eine E-Mail an info@Lokalpetition.de widerrufen werden.  <br />
    <br />8.  Änderung<br /><br />
    Wir behalten uns das Recht vor, diese AGB von Zeit zu Zeit zu überarbeiten, um Folgendes besser wiederzugeben:<br />
    -Gesetzesänderungen<br />
    -Neue regulatorische Anforderungen<br />
    -Verbesserungen oder Erweiterungen unserer Dienste. <br />
    Wenn sich eine Änderung auf Ihre Nutzung der Dienste oder auf Ihre Rechte als Nutzer unserer Dienste auswirkt, benachrichtigen wir Sie vor dem Datum des Inkrafttretens der Änderung, indem wir eine E-Mail an die mit Ihrem Konto verknüpfte E-Mail-Adresse schicken oder indem wir eine entsprechende Nachricht im Produkt selbst einblenden.  Das Datum des Inkrafttretens der aktualisierten AGB liegt mindestens 30 Tage nach dem Datum der Benachrichtigung.  Wenn Sie mit den Änderungen nicht einverstanden sind, müssen Sie Ihr Konto vor deren Inkrafttreten kündigen, indem Sie die Dienste nach Inkrafttreten der Änderungen weiterhin nutzen, stimmen Sie den geänderten AGB zu.  <br /><br />
  </div>
  );
}

export default Agb;
